#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require('config/init.php');

$load = require($frameworkDir . '/vendor/autoload.php');
#测试：加入外部命名空间
#$load->addPsr4("aaa\\",'E:/www/aaa');
require($frameworkDir . '/vendor/yiisoft/yii2/Yii.php');
require($frameworkDir . '/common/config/bootstrap.php');
require($frameworkDir . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require($frameworkDir . '/common/config/main.php'),
    require($frameworkDir . '/common/config/main-local.php'),

    require(__DIR__ . '/config/main-console.php'),#关于console专属配置
    require(__DIR__ . '/config/main-local.php'),
    require(__DIR__ . '/config/main-db.php')
);

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
