#!/bin/bash
#
# Copyright (C) 2016 Bluedon. All rights reserved.
# Author: Linfan Hu (hlf@chinabluedon.cn)
# Date: 2016/11/23
#

chmod a+x *.sh
chmod a+x waf_update/*.sh

tar -czf waf_update.tar.gz waf_update/

read -s -p "Input password: " PASSWD
if [ -z "$PASSWD" ]; then
    echo "password must not null"
    exit 1
fi

echo ""

read -s -p "confirm password: " PASSWD2
if [ "$PASSWD2" != "$PASSWD" ]; then
    echo "password not match"
	rm -f waf_update.tar.gz
    exit 1
fi

echo ""

openssl aes-128-cbc -salt -k $PASSWD -in waf_update.tar.gz -out waf_update.tar.gz.enc
if [ $? -ne 0 ]; then
    echo "Cannot encrypt tar ball"
    exit 1
fi

openssl dgst -md5 waf_update.tar.gz.enc | awk '{print $2}' > waf_update.md5
if [ $? -ne 0 ]; then
    echo "Cannot calculate md5 for tar ball"
    exit 1
fi

read -p "Input upgrade pack name: " TAR_NAME
if [ -z "$TAR_NAME" ]; then
    echo "Error: No upgrade pack name"
    exit 1;
fi

mkdir -p $TAR_NAME

# if version.txt is commented, it'll be generated by svn exporter
VAR=`cat version.txt | grep "#"`
if [ -z "$VAR" ]; then
    cp -f version.txt $TAR_NAME/
else
    cp -f waf_update/version.txt $TAR_NAME/
fi

cp -f update_wizard.sh $TAR_NAME/
mv waf_update.tar.gz.enc $TAR_NAME/
mv waf_update.md5 $TAR_NAME/

tar -czf $TAR_NAME.tar.gz $TAR_NAME/
rm -rf $TAR_NAME/
rm -f waf_update.tar.gz

