<?php
namespace app\controllers;

use Yii;
use app\logic\BaseController;

/**
 * 安全管理 - 配置管理 - 端口扫描
 */
class PortScanController extends BaseController{

    public function actionIndex()
    {
        if( Yii::$app->request->get('op')=='detail' ) return ($this->model)::getDetail();
        return parent::actionIndex(); // TODO: Change the autogenerated stub
    }

    public function actionCreateSite($id){
        return parent::actionUpdate($id);
    }

    public function actionConfig()
    {
        $this->model = '\\app\\models\\PortScanConfig';
        if(Yii::$app->request->get('op')=='show'){
            $model = new $this->model;
            $result = $model->get(true);
            Yii::$app->sysJsonMsg->data(true, $result);
        }
        return parent::actionConfig();
    }


}
