USE waf_hw;

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `host_family_list`
-- ----------------------------
DROP TABLE IF EXISTS `host_family_list`;
CREATE TABLE `host_family_list` (
  `id` int(11) NOT NULL auto_increment,
  `parent_id` int(11) default '0',
  `desc` varchar(255) character set utf8 default NULL,
  `priority` int(11) default '0',
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=171 DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records of host_family_list
-- ----------------------------
INSERT INTO `host_family_list` VALUES ('10', '9', 'Windows IE 浏览器漏洞检测', '2');
INSERT INTO `host_family_list` VALUES ('9', '0', 'Windows漏洞检测', '9');
INSERT INTO `host_family_list` VALUES ('8', '1', 'IBM Lotus漏洞检测', '7');
INSERT INTO `host_family_list` VALUES ('7', '1', 'Nginx漏洞检测', '6');
INSERT INTO `host_family_list` VALUES ('6', '1', 'SSL模块漏洞检测', '5');
INSERT INTO `host_family_list` VALUES ('5', '1', 'Apache Tomcat漏洞检测', '4');
INSERT INTO `host_family_list` VALUES ('4', '1', 'IBM WebSphere漏洞检测', '3');
INSERT INTO `host_family_list` VALUES ('3', '1', 'Apache漏洞检测', '2');
INSERT INTO `host_family_list` VALUES ('2', '1', '微软IIS漏洞检测', '1');
INSERT INTO `host_family_list` VALUES ('1', '0', 'Web服务器漏洞检测', '1');
INSERT INTO `host_family_list` VALUES ('11', '9', 'Office漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('12', '9', '.Net漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('14', '9', 'Windows应用软件漏洞检测', '3');
INSERT INTO `host_family_list` VALUES ('16', '9', 'Windows系统漏洞检测', '1');
INSERT INTO `host_family_list` VALUES ('17', '0', 'MacOS漏洞检测', '17');
INSERT INTO `host_family_list` VALUES ('18', '17', 'Mac应用软件漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('19', '17', 'Mac系统安全漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('20', '0', 'UNIX漏洞检测', '20');
INSERT INTO `host_family_list` VALUES ('21', '20', 'Unix账户漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('22', '20', '通用Unix漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('23', '20', 'SSH漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('24', '0', '数据库漏洞检测', '24');
INSERT INTO `host_family_list` VALUES ('25', '24', 'MYSQL数据库漏洞检测', '2');
INSERT INTO `host_family_list` VALUES ('26', '24', 'MSSQL数据库漏洞检测', '1');
INSERT INTO `host_family_list` VALUES ('27', '24', 'ORACLE数据库漏洞检测', '3');
INSERT INTO `host_family_list` VALUES ('28', '24', 'SYBASE数据库漏洞检测', '6');
INSERT INTO `host_family_list` VALUES ('29', '24', 'DB2数据库漏洞检测', '4');
INSERT INTO `host_family_list` VALUES ('30', '0', 'CGI漏洞检测', '30');
INSERT INTO `host_family_list` VALUES ('31', '30', 'PHP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('32', '30', 'SQL注入漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('33', '30', '跨站漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('34', '67', '输入验证/认证检测漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('35', '30', '代码执行漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('36', '30', '目录遍历漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('37', '30', '包含漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('38', '67', '权限提升漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('39', '30', '信息泄露漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('40', '30', '通用CGI漏洞检测', '1');
INSERT INTO `host_family_list` VALUES ('41', '0', 'DNS漏洞检测', '41');
INSERT INTO `host_family_list` VALUES ('42', '41', '通用DNS漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('43', '41', 'ISC BIND漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('44', '41', 'PowerDNS漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('45', '0', 'FTP/TFTP漏洞检测', '45');
INSERT INTO `host_family_list` VALUES ('46', '45', 'ProFTPD漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('47', '45', 'WU-FTPD漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('48', '45', 'Serv-U漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('49', '45', 'TYPSoft FTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('50', '45', 'Wing FTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('51', '45', '其他FTP漏洞检测', '100');
INSERT INTO `host_family_list` VALUES ('52', '0', '虚拟化漏洞检测', '52');
INSERT INTO `host_family_list` VALUES ('53', '52', '通用Vmware漏洞检测', '1');
INSERT INTO `host_family_list` VALUES ('54', '0', '网络设备漏洞检测', '54');
INSERT INTO `host_family_list` VALUES ('55', '54', 'Cisco网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('56', '54', 'Juniper网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('57', '54', 'Citrix网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('60', '54', '其他网络设备漏洞检测', '100');
INSERT INTO `host_family_list` VALUES ('61', '0', '邮件服务器漏洞检测', '61');
INSERT INTO `host_family_list` VALUES ('62', '61', 'Sendmail漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('63', '61', '微软Exchange漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('64', '61', 'Ipswitch Imail漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('65', '61', 'Postfix漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('66', '61', '其他邮件服务器漏洞检测', '100');
INSERT INTO `host_family_list` VALUES ('67', '0', '杂项漏洞检测', '67');
INSERT INTO `host_family_list` VALUES ('68', '67', 'Finger漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('69', '67', '操作系统识别', '0');
INSERT INTO `host_family_list` VALUES ('70', '67', '注册表漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('71', '67', 'Asterisk系统漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('72', '67', 'Quagga系统漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('73', '67', '其他漏洞检测', '102');
INSERT INTO `host_family_list` VALUES ('74', '20', '缓冲区溢出漏洞检测', '74');
INSERT INTO `host_family_list` VALUES ('164', '20', 'NFS漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('76', '67', '后门检测', '76');
INSERT INTO `host_family_list` VALUES ('77', '20', '拒绝服务漏洞检测', '77');
INSERT INTO `host_family_list` VALUES ('78', '67', 'P2P漏洞检测', '78');
INSERT INTO `host_family_list` VALUES ('169', '67', 'BlackBerry漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('80', '67', 'SNMP漏洞检测', '80');
INSERT INTO `host_family_list` VALUES ('81', '1', 'Squid漏洞检测', '10');
INSERT INTO `host_family_list` VALUES ('82', '1', 'lighttpd漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('83', '1', 'Sun iPlanet Web漏洞检测', '13');
INSERT INTO `host_family_list` VALUES ('84', '1', 'Netscape Enterprise漏洞检测', '12');
INSERT INTO `host_family_list` VALUES ('85', '1', 'Oracle HTTP Server漏洞检测', '14');
INSERT INTO `host_family_list` VALUES ('86', '1', 'Resin漏洞检测', '8');
INSERT INTO `host_family_list` VALUES ('87', '1', 'Zeus漏洞检测', '19');
INSERT INTO `host_family_list` VALUES ('88', '1', 'Cherokee漏洞检测', '17');
INSERT INTO `host_family_list` VALUES ('89', '1', 'Abyss Web Server漏洞检测', '20');
INSERT INTO `host_family_list` VALUES ('90', '1', 'Weblogic漏洞检测', '9');
INSERT INTO `host_family_list` VALUES ('91', '1', 'HP System Management Homepage漏洞检测', '16');
INSERT INTO `host_family_list` VALUES ('92', '1', 'RaidenHTTPD漏洞检测', '18');
INSERT INTO `host_family_list` VALUES ('93', '9', 'Firefox漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('94', '9', 'Opera漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('95', '9', 'Adobe漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('96', '9', 'Skype漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('97', '9', 'Google漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('98', '9', 'Safari漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('99', '9', 'RealNetworks/RealPlayer漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('100', '9', 'Sun Java漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('101', '9', 'Autodesk漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('102', '9', 'Landesk漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('103', '9', 'Winamp漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('104', '9', 'Yahoo漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('105', '9', 'QuickTime漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('106', '9', 'Teamviewer漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('107', '24', 'PostgreSQL数据库漏洞检测', '5');
INSERT INTO `host_family_list` VALUES ('108', '24', 'Firebird数据库漏洞检测', '9');
INSERT INTO `host_family_list` VALUES ('109', '24', 'SAP MaxDB数据库漏洞检测', '7');
INSERT INTO `host_family_list` VALUES ('110', '24', 'solidDB数据库漏洞检测', '8');
INSERT INTO `host_family_list` VALUES ('111', '45', 'WS_FTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('112', '45', 'Golden FTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('113', '45', 'RaidenFTPD漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('114', '45', 'SunFTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('115', '45', 'War-FTPD漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('116', '45', 'FileZilla漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('117', '45', 'Xlight FTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('118', '45', 'Ipswitch漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('119', '45', 'CesarFTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('120', '52', '通用Virtual Box漏洞检测', '2');
INSERT INTO `host_family_list` VALUES ('122', '54', 'MikroTik RouterOS漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('123', '54', 'DD-WRT网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('124', '54', 'D-link网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('125', '54', 'NETGEAR网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('126', '54', 'F5网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('127', '54', 'Websense网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('128', '54', 'EMC网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('129', '54', 'Fortinet网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('130', '54', '北电网络（Nortel）网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('131', '54', 'ZyXEL网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('132', '61', 'Kerio MailServer漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('133', '61', 'Youngzsoft漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('134', '61', 'Exim漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('135', '61', 'GoodTech漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('136', '61', 'NetWin dmail漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('137', '61', 'MDaemon漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('138', '20', 'Samba漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('168', '54', 'Check Point网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('140', '67', 'IBM Tivoli漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('141', '54', '趋势科技网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('142', '67', '服务检测', '101');
INSERT INTO `host_family_list` VALUES ('143', '67', 'Mozilla Thunderbird漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('144', '67', 'SeaMonkey漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('145', '30', '文件上传漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('146', '67', '越权访问漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('147', '1', '其他Web服务器漏洞检测', '100');
INSERT INTO `host_family_list` VALUES ('148', '20', 'Unix RPC漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('149', '61', 'IMAP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('150', '54', '3COM网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('151', '54', 'BlueCoat网络设备漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('152', '20', 'Solaris漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('153', '20', 'Novell漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('154', '20', 'FreeBSD漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('155', '20', 'RedHat漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('156', '54', 'SonicWall漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('157', '9', '防病毒软件漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('158', '9', 'ActiveX漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('159', '30', 'ASP.NET漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('160', '45', 'TFTP漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('161', '1', 'Zope漏洞检测', '15');
INSERT INTO `host_family_list` VALUES ('162', '20', 'OpenOffice漏洞检测', '0');
INSERT INTO `host_family_list` VALUES ('163', '9', 'Flash Player漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('165', '52', 'KVM漏洞检测', '3');
INSERT INTO `host_family_list` VALUES ('166', '52', 'OpenStack漏洞检测', '4');
INSERT INTO `host_family_list` VALUES ('167', '9', 'Foxit漏洞检测', '11');
INSERT INTO `host_family_list` VALUES ('170', '67', 'VERITAS NetBackup漏洞检测', '0');
