#!/usr/bin/env python
#-*-encoding:UTF-8-*-

output_dict={'Version source':'源版本',
'Installed version':'已安装版本',
'Fixed version':'修复版本',
'The following certificate was at the top of the certificate':'如下证书在证书链顶端',
'chain sent by the remote host, but is signed by an unknown':'但是被一个未知证书授权机构签名',
'The following certificate was found at the top of the certificate':'如下证书在证书链顶端',
'chain sent by the remote host, but is self-signed and was not':'但是它是自签名的，',
'found in the list of known certificate authorities':'而且不在已知的证书授权机构列表中',
'The following configuration indicates that the remote service':'如下配置表明，远程主机上',
'may be vulnerable to the CRIME attack':'可能存在CRIME攻击漏洞',
'A MySQL server is running on this port':'MySQL server运行在该端口上',
'This port supports resuming SSLv3 sessions':'该端口允许恢复SSLv3会话',
'external URL was gathered on this web server ':'个外部链接在当前Web server上被发现',
'external URLs were gathered on this web server':'个外部链接在当前Web server上被发现',
'The following directories were discovered':'发现如下目录',
'While this is not, in and of itself, a bug, you should manually inspect':'虽然这并不是一个bug，',
'these directories to ensure that they are in compliance with company':'但是你需要手动检查，确保他们符合公司的',
'security standards':'安全标准',
'was able to confirm that the following compression method is ':'可以确认目标主机支持如下压缩方法',
'was able to confirm that the following compression methods are':'可以确认目标主机支持如下压缩方法',
'supported by the target':'',
'Here is the list of SSL PFS ciphers supported by the remote server':'下面是远程服务器支持SSL加密的PFS列表',
'The fields above are':'上面的字段是',
'server is running on this port':'server运行在该端口上',
'NULL sessions are enabled on the remote host':'远程主机开启了NULL会话',
'Could not connect to the registry because':'无法连接到注册表中，因为',
'According to LLMNR, the name of the remote host is':'根据LLMNR，远程主机的名称为',
'It was not possible to log into the remote host via smb':'无法通过smb账户登录到远程主机',
'invalid credentials':'凭据无效',
'The following pages are protected':'如下页面被保护',
'was able to identify the following PHP version information':'可以识别出如下PHP版本信息',
'was able to execute the command':'能够执行下面命令',
'The following CGI have been discovered':'发现如下CGI程序',
'certificate authority':'',
'was able to exploit the cross-site scripting flaw using the following URL':'通过以下URL能够利用跨站脚本漏洞',
'Version':'版本',
# 'version':'版本',
'versions':'版本',
'of 3D-FTP is installed under':'3D-FTP安装在',
'of the 3ivx MPEG-4 compression suite is installed under':'3ivx MPEG-4的压缩套件安装在',
'The following instance':'以下实例',
'installed on the remote host':'安装在远程主机',
'The following files are affected':'以下文件受影响',
'was able to gain access using the following credentials':'能够使用下列凭据访问',
'Password':'密码',
'Username':'用户名',
'Pass      ':'密码',
'Repository':'版本库',
'host using the following URL':'主机使用下面url:',
'Here are the repeated contents of the file /etc/passwd that':'下面是/etc/passwd文件里的重复内容',
'Nessus was able to read from the remote host':'Nvscan能够从远程主机读取',
'Here is the ACAP servers SSL certificate that Nessus was able to':'下面是ACAP服务器的SSL证书，Nvscan能够',
'collect after sending a STARTTLS command':'在发送STARTTLS命令后收集',
'was able to verify the vulnerability using the following URL':'通过以下URL能够验证该问题：',
'ActiveMQ Web Console':'ActiveMQ Web Console',
'Here are the (repeated) contents of the file /etc/passwd that':'下面是/etc/passwd的内容',
'was able to gain access using the following information':'能够使用以下信息',
'It was possible to execute the command':'可以执行命令',
'host, which produces the following output':'产生如下输出的主机',
'Path':'路径',
'Fix ':'修复版本',
'A vulnerable version of Adobe Acrobat was detected':'检测到易受攻击的Adobe Acrobat版本',
'Additionally, the following file has not been deleted or renamed':'此外，以下的文件已经被删除或者重命名',
'Comment':'注释',
'has not been deleted or renamed.':'是否已被删除或重命名。',
# 'Product':'产品',
'of Adobe Download Manager is installed as':'Adobe 下载管理工具被安装在',
'The following install':'下面的安装',
'has determined that the installed version of Breeze is':'已经确定Breeze的安装版本是',
'was able to read the following password from the installation':'能够从安装过程中阅读下面的密码',
'log but has not tried to validate it':'登录但一直没有试图验证它：',
'The following vulnerable instance':'下面易受攻击的程序',
'installed on the':'被安装在',
'was able to write to the following file on the remote host':'能够在远程主机上写入以下文件：',
'discovered the following vulnerable instance(s) of the file on':'发现脆弱的文件实例在',
'Supported version(s)':'支持的版本',
'Application ':'应用',
'The following install of Adobe Media Encoder was found on the':'发现Adobe Media加密器安装在',
'found following vulnerable HTTPChannel endpoint':'发现下列脆弱的HTTP通道的端点：',
'File':'文件',
'File timestamp':'文件时间戳',
'Fixed timestamp':'修复时间戳',
'The following unsupported instance':'不支持的情况下',
'of Adobe Acrobat is installed as':'Adobe Acrobat安装在',
'A vulnerable version of Adobe Reader was detected':'检测到脆弱的Adobe Reader版本',
'discovered the following installation':'发现安装了',
'found JavaScript enabled for the following user':'发现下列用户启用了JavaScript',
'AOL Instant Messenger version':'AOL Instant Messenger版本',
'is installed on the remote host.':'被安装在远程主机上。',
'was able to exploit the issue to retrieve the contents of':'能够利用这个问题来检索内容',
'using the following request':'使用以下请求',
'Installed Technology Level ':'产品安装等级：',
'uncovered the following set of default credentials':'发现下列一组默认凭据',
'was able to verify the vulnerability using the following':'能够使用下面的请求验证漏洞',
'which reports the email address as in use:':'报告正在使用的邮件地址',
'along with the following request':'连同下列要求',
'which reports the email address is ok to use:':'报告可以使用的邮件地址',
'The output of the command':'执行此命令',
'OS Type':'操作系统类型',
'of the Altiris Client Agent is installed under':'Altiris 客户代理安装在',
'Class identifier':'种类标示符',
'Filename':'文件名',
'was able to gather the following information from the remote':'能够从远程Altiris部署服务器收集以下信息',
'was able to successfully execute the':'能够成功执行',
'A vulnerable version of Altiris.Web.NS.dll was found':'发现易受攻击的Altiris.Web.NS.dll版本：',
'was able to log in using the default Administrator password':'能够使用默认的管理员密码登录',
'and access the following device information':'和访问以下设备信息',
'Nessus was able to verify the issue with the following queries and':'设备可以用下面的查询验证问题',
'Existing User':'存在的用户',
'Response Title':'标题',
'Invalid User':'无效用户',
'Here are the contents of the file /etc/passwd that':'这是文件/etc/passwd的内容',
'was able execute the command id on the remote host':'可以再远程主机上执行“id”命令',
'Here are the contents of the initial directory':'这里是初始目录的内容：',
'was able to gain access to the administrative interface using':'能够登录管理界面',
'remote host by sending the following request':'远程主机，通过发送下面请求',
'was able to execute the command ECHO on the remote host using':'可以在远程主机上执行ECHO命令',
'was able to exploit the issue using the following URL':'通过以下URL可以利用该漏洞',
'was able to verify the issue using the following request':'通过以下请求可以验证该问题',
'verified this by sending the following request':'通过发送下列请求验证',
'determined the server is unpatched and is not using any':'确定服务器是未打补丁的',
'of the suggested workarounds by making the following requests':'并且没有通过使用如下请求去使用推荐的解决办法',
'Here are the contents of the':'这是CGI脚本的内容',
'The TroubleShooter servlet is accessible as':'疑难解答servlet的访问为',
'Here is the status of the remote APC UPS':'远程APC UPS状态：',
'was able to collect the following information from the':'能够从在远程主机上运行的服务器收集以下的信息',
'was able to create the following directory on the remote':'可以在远程主机上创建如下目录',
'host, under the directory in which ArGoSoft Mail Server is':'创建的目录在ArGoSoft Mail Server 的安装目录下',
'The output of the root directory is':'根目录的输出是',
'The remote version of the software is':'远程主机上该软件的版本是',
'could log into the web management console using the':'可以登录web管理接口，通过使用',
'was able to use the backdoor to retrieve the contents of':'能够使用后门来检索内容',
'Here is some information collected from the remote agent':'这是从远程代理收集到的一些信息',
'collected the following information about the remote AFP service':'收集远程AFP服务的以下信息',
'Server name':'服务器名称',
'Machine type':'机器类型',
'The following HTTP response header was received after requesting the':'请求后收到以下HTTP响应头',
'was able to retrieve the source of':'能够检索到资源',
'Here are the repeated contents of ARIs config file that':'这是ARIs 配置文件的内容',
'SIP banner':'SIP banner信息',
'was only able to detect this issue by looking at the':'通过应用程序版本号检测到这个问题',
'applications version number. Please confirm this issue exists by':'请使用下面这个url判断是否存在非持久的跨站脚本攻击',
'attempting a non-persisent XSS attack using the following URL':'以验证该问题',
'Note that this URL requires authentication.':'注意下面这个需要认证。',
'was able to decrypt the following registry key':'能够解密以下注册表密钥',
'found an affected version of':'发现受影响的版本',
'was able to learn the following information about the remote':'能够获得以下信息关于远程',
'Here is an excerpt from the remote /etc/passwd file':'下面是从远程的/etc/passwd文件的摘录',
'was able to verify the issue using the following URL':'通过以下URL能够验证该问题',
'AWStats default page, awstats.pl, was found to exist on the web':'发现AWStats 默认页面',
'was able to exploit the flaw using following URL':'可以通过以下URL利用该漏洞',
'based on the following title on the initial login page':'根据下面登陆页面的标题',
'Barracuda Spam & Virus Firewall':'梭鱼垃圾邮件和病毒防火墙',
'was able to read from the remote host':'可以从远程主机中读取',
'was able to access base_main.php without authentication':'无需鉴权即可访问base_main.php文件',
'executed the following BeanShell/Java code':'执行如下BeanShell/Java代码',
'Which returned the following JRE version':'返回如下JRE版本',
'is running on the remote host.':'正在远程主机上运行。',
'was able to exploit the issue by sending the following':'能够利用该问题通过发送以下',
'put request':'PUT请求',
'was able to retrieve the contents of \'.svn/entries\' using the':'能够检索到.svn/entries的内容通过使用',
'The host name':'主机名',
'Database name:':'数据库名称',
'Database port:':'数据库端口',
'Service name':'服务名',
'Service path':'服务路径',
'Fixed build':'修复版本',
'Installed build version':'安装的版本',
'Fixed build version':'修复版本',
'Build version':'编译版本',
'Fixed build version':'修复版本',
'Current engine version':'引擎当前版本：',
'Fixed engine version':'引擎修复版本',
'Installed DLL version':'已安装动态链接库版本',
'Fixed DLL version':'动态链接库修复版本',
'Product name':'产品名称',
'Engine version':'引擎版本',
'Product version':'产品版本',
'Should be at least':'版本至少为',
'Installed file version':'文件安装版本',
'Fixed file version':'文件修复版本',
'Solution':'解决方案',
'*** Note that Nessus did not actually check for the flaw since':'***注意Nvscan不会实际检查这个问题，因为',
'*** safe checks are enabled, so this might be a false positive.':'***启用了“安全检测”，所以这可能是个误报。',
'Installed System Software version':'已安装软件版本',
'Fixed System Software version    ':'修复软件版本',
'Model':'模块',
'Supported Versions':'支持的版本',
'Installed build ':'已安装编译版本',
'Fixed build':'修复版本',
'Build number':'构建版本号',
'Patch(es)':'补丁',
'Virus signatures':'病毒签名',
'Installed release':'已安装版本',
'Fixed release':'修复版本',
'Recommended release':'推荐版本',
'engine installed version':'引擎已安装版本',
'engine recommended version':'引擎推荐版本',
'Detected version':'版本检测',
'Cisco Bug ID':'Cisco 漏洞 ID',
'IOS version':'IOS版本',
'Device':'设备',
'Software version':'软件版本',
'Component':'组件',
'Node name':'节点名称',
'Product identifier':'产品识别码',
'Application':'应用程序',
'To disable these methods, add the following lines for each virtual':'增下以下内容到每个虚拟主机配置文件上',
'host in your configuration file':'来关闭这些方法',
'by the Basic authentication scheme':'通过基本的鉴权模式',
'Installed build date':'已安装版本日期',
'Fixed build date':'已修复版本日期',
'This FTP server does not support':'该FTP服务器不支持',
'Contents of robots.txt':'robots.txt文件内容',
'was able to verify the vulnerability exists using the following':'通过以下方法可以验证该漏洞的存在',
'The script failed in making a socket connection to the target system':'该脚本无法在以前的连接已经起效后作出一个套接字连接到目标系统',
'after a previous connection worked.  This may affect the completeness':'这可能会影响报表的完整性',
'of the report and you might wish to rerun this test again on the':'你可能希望在目标系统上再次运行这个测试',
'targeted system.':'',
'The remote host name is':'远程主机名',
'appears to be installed on the remote host.':'似乎安装在远程主机上。',
'is installed as':'装在',
'Last update:':'最后更新',
'read from the remote host':'从远程主机中读取',
'on the remote host using the following URL':'远程主机上使用以下URL',
'Based on its build date,':'基于编译日期，',
'needs to be updated.':'需要更新',
'It was possible to log into the remote Cisco device using the':'可以登陆到思科设备使用',
'following credentials':'如下认证：',
'command, which returned in part':'命令，将返回',
'Cisco Email Security Appliance':'思科的电子邮件安全设备',
'was able to verify the issue exists by requesting the following':'通过发送以下请求验证该问题是否存在',
'URL and examining the response header':'url并检查响应头：',
'Cisco Prime LAN Management Solution':'思科局域网管理解决方案',
'Cisco Prime NCS / WCS Health Monitor':'思科Prime NCS/ WCS的健康监控',
'Cisco Prime Security Manager':'思科Prime安全管理',
'Cisco Content Security Management Appliance':'Cisco内容安全管理设备',
'SSL port':'SSL 端口',
'SHA1 fingerprint':'SHA1 指纹',
'Cisco TelePresence Multipoint Switch':'思科网真多点交换机',
'Cisco UCS Manager':'思科 UCS 管理',
'Cisco Unified Operations Manager':'Cisco Unified Operations Manager',
'Upgrade to Cisco AnyConnect Secure Mobility Client':'升级到Cisco anyconnect安全移动客户端',
'Cisco Web Security Appliance':'思科的网络安全设备',
'of the Citrix ICA Client is installed under':'Citrix ICA的客户端是安装在：',
'of the Citrix Password Manager Agent is installed under':'Citrix密码管理器代理安装在',
'of the Citrix Password Manager Service is installed under':'Citrix密码管理服务安装在',
'and received the following response from the remote server':'从远程服务器收到的响应',
'sent the following TRACE request':'发送如下TRACE请求',
'Alternatively, note that Apache version 1.3.34, 2.0.55, and 2.2':'注意，apache版本1.3.34, 2.0.55,以及2.2',
'support disabling the TRACE method natively via the \'TraceEnable\'':'支持通过TraceEnable开关关闭TRACE方法',
'directive.':'',
'Firewall host   ':'防火墙主机',
'SmartCenter host':'SmartCenter主机',
'was able to obtain a cross-domain policy file from the remote':'检测到跨域策略文件',
'following URL':'如下URL',
'Could not connect to':'无法连接到',
'It is possible to log into the Tomcat Manager web app at the':'可以登录到Tomcat Web应用程序,通过',
'with the':'使用',
'The remote DNS server uses non-random ports for its':'远程DNS服务器发送请求时使用非随机端口',
'DNS requests. attacker may spoof DNS responses':'攻击者可以欺骗DNS响应',
'List of used ports':'使用的端口列表如下',
'The remote web server supports the following methods':'远程Web服务器支持如下方法',
'the file \'/aosewv1.html\' has been uploaded':'文件 /aosewv1.html已被上传',
'the file \'/aosewv1.html\' has been deleted':'文件 /aosewv1.html已被删除',
'The following certificate was part of the certificate chain':'如下证书是远程主机证书链的一部分',
'sent by the remote host, but has expired':'但是该证书已经过期了',
'Use the URLScan tool to deny HTTP TRACE requests or to permit only the':'使用URLScan工具禁用HTTP TRCE请求，或者只开放满足站点需求的方法',
'methods needed to meet site requirements and policy':'',
'The terminal services encryption level is set to':'终端服务加密级别设置为',
'discovered the':'发现',
'that calls phpinfo':'调用了phpinfo',
'Here is the list of weak SSL ciphers supported by the remote server':'这里是弱SSL密码的远程服务器支持列表',
'Here is the list of medium strength SSL ciphers supported by the remote server':'这里是一个中等强度的SSL加密的远程服务器支持列表',
'The server allowed the following session over SSLv3 to be resumed as follows':'服务器允许在SSLv3上恢复会话',
'The SSL certificate has already expired':'SSL证书已过期',
'It was possible to bind to the \\browser pipe':'可以绑定到\\browser管道',
'The following SOP configuration file can be accessed directly':'下面的SOP配置文件可以直接访问',
'The following SOP document is accessible':'下面的SOP文件可以直接访问',
'The web root physical path is':'Web根目录的物理路径',
'By making a series of requests, Nessus was able to determine the':'通过一系列请求，NVscan确认',
'following phpMydmin installation is vulnerable':'phpMydmin易受攻击',
'The following page / argument is potentially affected':'以下页面 / 参数可能受影响',
'The CGI was found under':'发现CGI程序',
'The terminal services encryption level is set to ':'终端服务加密级别设置为',
'Give Nessus credentials to perform local checks':'需要给Nvscan提供账户信息来做更多的检查',
'The Common Name in the certificate is':'证书中的通用名称是',
'The host name known by Nessus is':'Nvscan发现主机名',
'The following pages use an X-Frame-Options response header':'以下页面使用X-Frame-Options响应头',
'Here is the browse list of the remote host':'下面是远程主机的列表',
'The default welcome page is from IIS':'默认的欢迎页面是来自IIS',
'The following office-related files are available on the remote server':'可在远程服务器上找到如下办公文件',
'The remote extensions are handled by the remote SP.NET server':'远程扩展由远程SP.NET服务器处理',
'CGI scanning will be disabled for this host because the host responds':'CGI扫描将被禁用',
'to requests for non-existent URLs with HTTP code 302':'因为主机响应一个不存在的URL时用的是302而不是404',
'rather than 404. The requested URL was':'所请求的URL是',
'request returns the following':'请求返回以下内容',
'This port supports resuming TLSv1 sessions':'该端口支持恢复TLSv1会话',
'web server seems to be running on this port':'web服务器似乎在这个端口上运行',
'The following instance of phpMydmin was detected on the remote host':'远程主机正在运行phpMyAdmin',
'The connector listing on this port supports the ajp13 protocol':'监听在该端口的连接器支持ajp13协议',
'The SSL certificate will expire within 60 days':'该SSL证书将在60天内过期',
'It was possible to extract the following information from the remote PPTP server':'可以从远程的PPTP服务器中提取以下信息',
'Here are the SMB shares available on the remote host when logged as xhlipxgm':'登录为xhlipxgm用户时，可用的SMB共享如下',
'\'ping\' request returned the following information about the remote':'ping 请求返回关于SQL实例的如下信息',
'SQL instance':'',
'of Microsoft Media Services is running on this port':'微软媒体服务是在这个端口上运行',
'SLP Service gent is listening on this port':'SLP服务监听在此端口',
'In addition, Nessus was able to learn that the agent knows about':'此外,Nvscan可以通过代理获取如下服务信息',
'the following services':'',
'The version of the remote DNS server is':'远程DNS服务器的版本是',
'The remote SSH daemon supports the following version of the':'远程SSH守护程序支持的以下版本的',
'SSH protocol':'SSH协议',
'The remote Oracle TNS listener replies with the following version':'远程Oracle TNS监听器回复以下版本',
'The following default sids have been found':'以下默认sids被发现',
'SSH supported authentication':'SSH支持的身份验证',
'The remote DNS server uses non-random ports for its':'远程DNS服务器使用非随机端口',
'DNS requests. attacker may spoof DNS responses':'攻击者可以欺骗DNS响应',
'does not resolve to an IP address':'与IP地址不匹配',
'The following authentication methods are advertised by the SMTP':'如下由SMTP提供的方法未加密',
'server without encryption':'',
'Source :':'源',
'Seen on':'查看',
'The certificate chain sent by the remote host is not in order':'远程主机发送的证书链未排序',
'On the following port(s)':'在如下端口上',
'The operating system was identified as':'操作系统被识别为',
'Page :':'页面:',
'Destination page':'目标页面',
'Input name':'输入用户名',
'An SMB':'SMB',
'A CIFS':'CIFS',
'Subject Name':'对象名称',
'Common Name':'统称',
'Issuer Name':'发行人名称',
'Serial Number':'序列号',
'Signature Algorithm':'签名算法',
'Not Valid Before':'该日期之前无效',
'Not Valid After':'该日期之后无效',
'Public Key Info':'公钥信息',
'Algorithm':'算法',
'Key Length':'密钥长度',
'Public Key':'公钥',
'Exponent':'指数',
'Signature Length':'签名长度',
'Signature':'签名',
'Extension':'延期',
'Subject Key Identifier':'密钥标识符',
'Key Identifier':'密钥标识符',
'ESS Controller version':'ESS Controller版本',
'was able to exploit the issue with the following credentials':'通过以下账户信息可以利用该漏洞',
'Here is the XMPP services SSL certificate that was able to':'下面是XMPP服务的SSL证书，能够',
'is installed on the remote host under':'安装在以下远程主机上',
'of Yahoo! Messenger is currently installed on':'Yahoo! Messenger目前安装在',
'identified the following affected file':'鉴别下面受影响的文件',
'The output of /bin/sh -c id is':'”/bin/sh -c id“的输出是',
'Note that clicking the Return to Zenphoto link will execute':'注意点击Zenphoto 返回的链接将执行',
'the JavaScript code and display an alert box to demonstrate the':'Javascript代码并弹出一个alert提示框去证明',
'was able to verify the issue exists using the following request':'可以验证该漏洞存在，通过使用如下请求',
'which executed the command':'执行命令',
'The remote host reported the following information to':'远程主机报告以下信息到',
'of STEngine.exe is installed under':'STEngine.exe的版本是安装在这个路径下',
'was able to access the admin panel with empty credentials':'是​​能够使用空凭据访问管理面板',
'host by sending the following request':'主机发送如下请求',
'The following certificate was found at the top of the certificate':'如下证书被发现',
'found in the list of known certificate authorities':'在已知的证书列表中',
'was able to verify the issue using the following request to':'验证该问题使用以下请求去',
'modify the status of album id':'修改相册id的状态',
'which resulted in the password reset of a WordPress account on the':'这将导致WordPress的账号上的密码重设在',
'remote host.  The affected user will likely receive an email':'远程主机。受影响的用户可能会受到邮件',
'informing them of this':'通知他们',
'Should be at least':'至少应为',
'was able to':'设备能',
'This cookie may have been set by IIS':'该cookie可能由IIS设置',
'The following directories require authentication':'如下目录要求授权',
'This cookie was set by Tomcat':'cookie 由Tomcat设置',
'servlet/jsp engine':'servlet/jsp 引擎',
'Here is the export list of':'下面是输出列表',
'compression is enabled':'启用压缩',
'exploit the issue by using the':'利用该问题通过',
'A web':'web',
'host key fingerprint':'密钥指纹',
'The remote SSH daemon supports the following version of the':'远程SSH守护程序支持的以下版本的',
'Install Interim Security Software Update for July 12th 2011 to correct the issue.':'安装Interim Security Software July 12th 2011更新可以修复该问题。',
'was able to exploit this issue using the following request':'通过如下请求可以利用该漏洞',
'was able to obtain the name of the NIS domain on the network':'能够获取网络的NIS域的名称',
'Here are the contents of the file boot.ini that ':'下面是boot.ini文件的内容',
'The output was':'输出信息',
'host to produce the following results':'主机产生以下结果',
'It was possible to login to the FTP service on the remote host':'能够登录到远程主机的FTP',
'with the following credentials':'通过以下凭据',
'These accounts have no passwords:':'这些帐户没有密码',
'host using the following request':'主机使用了下列请求',
'The remote service supports tunneling the following services':'远程服务支持以服务的隧道传输',
'sent a non-recursive query for':'发送一个非递归查询',
'was able to verify the issue exists using the following URL':'通过以下URL可以验证该问题',
'was able to verify the issue exists using the following request':'是​​能够使用下列要求验证存在的问题',
'was able to verify this issue with the following request':'通过以下请求可以验证该问题',
'was able to verify the issue exists using the following':'验证漏洞存在，通过使用如下',
'The following information was extracted from this service':'以下信息是从该服务中获取的',
'was able to verify the issue the following URL':'通过以下URL能够验证该漏洞',
'The following directories were found to be browsable:':'下列目录发现可以进行浏览',
'was able to verify the issue by manipulating the list of':'可以验证该漏洞，通过利用如下列表',
'was able to verify the issue based on the HTTP response header':'能够基于HTTP响应头验证此问题',
'In order to demonstrate this issue, a request such as the following':'为了证明这个问题，如下的一个请求',
'can be made from the command line as a browser may not properly':'可以通过命令行产生，而浏览器不一定会',
'Here is the LDAP servers SSL certificate that was able to':'下面是LDAP服务器的SSL证书使得能够',
'An unknown version of Land Down Under is installed under':'未知版本的Land Down Under安装在',
'URL(s) associated with the Status module enabled':'模板在启用状态下的URL',
'was able to detect the vulnerability using the following':'是能够使用以下信息检测漏洞',
'was able to execute the command id on the remote host,':'能够执行远程主机上的命令，',
'Clicking on this URL will demonstrate the flaw':'点击这个URL将显示这个漏洞',
'Here are the contents of Loudblogs config file that':'下面是Loudblogs 配置文件的内容',
'host, under the directory in which Macallan is installed:':'主机，在Macallan 安装的目录下',
'Installed product build version':'安装的产品版本',
'NativeLanManager fingerprint':'NativeLanManager 指纹',
'Fixed NativeLanManager fingerprint':'NativeLanManager修复版本指纹',
'The remote version of iPhoto is':'远程主机的iPhoto版本是',
'Installed version of Numbers':'安装的版本号',
'Framework':'组件',
'of QuickTime is currently installed':'QuickTime 当前被安装',
'was able to exploit this issue to bypass authentication and':'能够利用该问题绕过认证',
'gain access to a page using the following request':'通过以下请求登录页面',
'ManageEngine Applications Manager':'ManageEngine应用程序管理',
'Note that you may first have to clear any cookies set by the':'请注意，您可能首先要清除由您的浏览器应用设置的任何的cookies。',
'application from your browser.':'',
'The remote extensions are handled by the remote ASP.NET server':'ASP.NET网页服务器的处理列表',
'Unfortunately, Nessus has been unable to find a way to recognize this':'nvscan无法找到一个方法来识别这个页面，所以一些CGI相关检查已被禁用。',
'page so some CGI-related checks have been disabled':'',
'to requests for non-existent URLs with HTTP code 301':'请求一个不存在的URL返回301',
'of phpMyAdmin was detected on the remote host':'的phpMyAdmin在远程主机上被检测到',
'(from banner)':'(从旗帜信息)',
'An SLP Service Agent is listening on this port':'SLP服务监听在此端口',
'Here are the SMB shares available on the remote host when logged as':'下面是远程主机上可用的SMB共享，登录为',
'The following directories are DAV enabled':'下面的目录启用DAV',
'This port supports resuming TLSv1 / SSLv3 sessions':'该端口支持恢复TLSv1/SSLv3会话',
'The following SOAP configuration file can be accessed directly':'下面的SOAP配置文件可以直接访问',
'The following SOAP document is accessible':'下面的SOAP文档可以访问',
'DNS requests. An attacker may spoof DNS responses':'DNS请求.攻击者可以欺骗DNS响应',
'following phpMyAdmin installation is vulnerable':'如下phpMyAdmin易受攻击',
'Session ID':'会话ID',
'Initial Cipher':'初始密钥',
'Resumed Cipher':'恢复密钥',
'The server allowed the following session over TLSv1 to be resumed as follows':'服务器允许在TLSv1上恢复会话',
'Note that Nessus stopped searching after one affected script was found':'需要注意的是，Nvscan在发现一个受影响的脚本后会停止搜索',
'For a complete scan, enable \'Thorough tests\' and re-scan':'对于一个完整的扫描，需要打开完整扫描开关，并重新扫描'
# 'The \'administrator\' account has no password set':'',
# 'The SMB tests will be done as':'',
# 'The following user is a member of the \'Administrators\' group':'',
# 'The following password policy is defined on the remote host':'',
# 'Minimum password len':'',
# 'Maximum password age (d)'
# 密码 history len
# 密码 must meet complexity requirements
# Minimum password age (d)
# Forced logoff time (s)
#  Not set
# Locked account time (s):

# Time between failed logon (s)
# Number of invalid logon before locked out (s)
# The remote host is up
# The host replied to an ARP who-is query
# Hardware address
# An ICMP ping
# A TCP ping
# A UDP ping
}